ALTER TABLE `inventoryequipment`
    ADD COLUMN `incRMAF` INT(11) NOT NULL DEFAULT '0' AFTER `ringid`,
    ADD COLUMN `incRMAS` INT(11) NOT NULL DEFAULT '0' AFTER `incRMAF`,
    ADD COLUMN `incRMAI` INT(11) NOT NULL DEFAULT '0' AFTER `incRMAS`,
    ADD COLUMN `incRMAL` INT(11) NOT NULL DEFAULT '0' AFTER `incRMAI`,
    ADD COLUMN `elemDefault` INT(11) NOT NULL DEFAULT '0' AFTER `incRMAL`;
